### ISSUE TITLE
Some questions about installing MAPGEN

### ISSUE THREAD

**Issue by HelloWorldLTY** [xinhe-lab/mapgen#1]
Hi, sorry to disturb you. I intend to install mapgen, but received this error:

Error: Failed to install 'mapgen' from GitHub:
  no lines available in input

Could you please help me solve this problem? Thanks a lot.

**Comment by kevinlkx** [comment]
Thanks for your interest. I don't see those problems when installing mapgen from Github. 

Which R version did you use? and did you install those other dependent packages?

**Comment by HelloWorldLTY** [comment]
Hi, many thanks for your reply. My R version is 4.1.3. Once I tried to install mapgen I met this problem, so I do not know if there are any extra packages I need. Thanks.

**Comment by kevinlkx** [comment]
Thanks for the information. Can you install these dependent R packages: tidyverse, data.table, bigsnpr, ggplot2, ggrepel, ggrastr, processx from CRAN, as well as GenomicRanges, plyranges, rtracklayer from Bioconductor? Then try install mapgen again

**Comment by HelloWorldLTY** [comment]
Hi, I have installed all of these packages but I still receive the same error. Even if I create a new environment, I still meet this problem.

**Comment by kevinlkx** [comment]
We have recently updated the package dependency and added some new functionality. It would be great if you can try to install again and see if this version (v0.3.12) works.
