### ISSUE TITLE
File Reading Error In The UK LD File

### ISSUE THREAD

**Issue by 1667857557** [xinhe-lab/mapgen#10]
Hi Dr.Luo
We encountered an error when using the [hg19] ukb_b37_0.1_chr8.R_snp.3392926_3783017.RDS and ukb_b37_0.1_chr8.R_snp.3392926_3783017.Rvar with the code below. All files are running well except for this region.Could you provide advice on how to resolve this issue? Thank you in advance!

```
library(data.table)
library(mapgen)
locus<-848
LD_blocks <- readRDS(system.file('extdata', 'LD.blocks.EUR.hg19.rds', package='mapgen'))
####locus 848 <- 
###chr | start | end | locus
##8 | 3392926 | 3783017 | 848
LDREF <- load_UKBB_LDREF(LD_blocks, 
                         locus = locus, 
                         LDREF.dir = "D:/fine_mapping", 
                         prefix = "ukb_b37_0.1")
```
![image](https://github.com/xinhe-lab/mapgen/assets/54109903/8cf6bccb-6371-4741-8b1e-4ca56e7af185)

Huang

**Comment by kevinlkx** [comment]
We made some updates to the finemapping functions of the package recently. You may reinstall the package and try again. Or it could be memory issue. You can try with a bigger memory.

**Comment by 1667857557** [comment]
Thanks for your reply,the problem has been resolved.
